<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\StackContract.Core\StackContract.Core.csproj" />
    <ProjectReference Include="..\StackContract.Compose\StackContract.Compose.csproj" />
    <ProjectReference Include="..\StackContract.Env\StackContract.Env.csproj" />
    <ProjectReference Include="..\StackContract.AppSettings\StackContract.AppSettings.csproj" />
    <ProjectReference Include="..\StackContract.Options\StackContract.Options.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><PackageId>StackContract.Engine</PackageId><RootNamespace>StackContract.Engine</RootNamespace><AssemblyName>StackContract.Engine</AssemblyName><Version>0.1.0</Version><Authors>Manuwel Munyai</Authors><PackageLicenseExpression>MIT</PackageLicenseExpression><RepositoryUrl>https://github.com/munyaimanuwel/stackcontract</RepositoryUrl><PackageProjectUrl>https://github.com/munyaimanuwel/stackcontract</PackageProjectUrl><GeneratePackageOnBuild>false</GeneratePackageOnBuild><IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>
