using System.CommandLine;
using StackContract.Core;
using StackContract.Engine;
var root = new RootCommand("StackContract — local-first stack/config contract checker");
var initCmd = new Command("init", "Write stackcontract.yml from compose / appsettings / options");
var composeOpt = new Option<string?>("--compose", "Path to compose YAML");
var overrideOpt = new Option<string?>("--override", "Path to compose override YAML");
var optionsOpt = new Option<string?>("--options", "Path to Options assembly for reflection");
var initAppsettingsOpt = new Option<string?>("--appsettings", "Path to appsettings.json");
var initEnvironmentOpt = new Option<string?>("--environment", "Environment name (appsettings.{Environment}.json)");
var forceOpt = new Option<bool>("--force", () => false, "Overwrite existing contract");
initCmd.AddOption(composeOpt); initCmd.AddOption(overrideOpt); initCmd.AddOption(optionsOpt); initCmd.AddOption(initAppsettingsOpt); initCmd.AddOption(initEnvironmentOpt); initCmd.AddOption(forceOpt);
initCmd.SetHandler((string? compose, string? ov, string? optionsAsm, string? appsettings, string? env, bool force) => { var cwd = Directory.GetCurrentDirectory(); var outPath = Path.Combine(cwd, "stackcontract.yml"); if (File.Exists(outPath) && !force) { Console.Error.WriteLine("stackcontract.yml already exists (use --force)."); Environment.Exit(2); } var doc = new InitService().Create(cwd, compose, ov, optionsAsm, appsettings, env); ContractLoader.Save(outPath, doc); Console.WriteLine($"Wrote {outPath}"); Environment.Exit(0); }, composeOpt, overrideOpt, optionsOpt, initAppsettingsOpt, initEnvironmentOpt, forceOpt);
var validateCmd = new Command("validate", "Validate compose + env + appsettings against contract");
var contractOpt = new Option<string>("--contract", () => "stackcontract.yml", "Contract path");
var profileOpt = new Option<string[]>("--profile", () => Array.Empty<string>(), "Active compose profile(s)") { AllowMultipleArgumentsPerToken = true };
var envExampleOpt = new Option<string?>("--env-example"); var envLocalOpt = new Option<string?>("--env-local"); var environmentOpt = new Option<string?>("--environment", "Environment name (appsettings.{Environment}.json)"); var formatOpt = new Option<string>("--format", () => "text", "text|json"); var strictOpt = new Option<bool>("--strict", () => false, "Promote warnings to errors");
validateCmd.AddOption(contractOpt); validateCmd.AddOption(profileOpt); validateCmd.AddOption(envExampleOpt); validateCmd.AddOption(envLocalOpt); validateCmd.AddOption(environmentOpt); validateCmd.AddOption(formatOpt); validateCmd.AddOption(strictOpt);
validateCmd.SetHandler((string contract, string[] profiles, string? envExample, string? envLocal, string? environment, string format, bool strict) => { try { var report = new ContractValidator().Validate(new ValidationOptions { ContractPath = contract, Profiles = profiles, EnvExamplePath = envExample, EnvLocalPath = envLocal, Environment = environment, Strict = strict, WorkingDirectory = Directory.GetCurrentDirectory() }); Console.Write(string.Equals(format, "json", StringComparison.OrdinalIgnoreCase) ? ReportFormatter.FormatJson(report) : ReportFormatter.FormatText(report)); Environment.Exit(report.HasErrors ? 1 : 0); } catch (Exception ex) { Console.Error.WriteLine(ex.Message); Environment.Exit(2); } }, contractOpt, profileOpt, envExampleOpt, envLocalOpt, environmentOpt, formatOpt, strictOpt);
var versionCmd = new Command("version", "Print tool version"); versionCmd.SetHandler(() => { var v = typeof(Program).Assembly.GetName().Version?.ToString(3) ?? "0.1.0"; Console.WriteLine($"stackcontract {v}"); Environment.Exit(0); });
root.AddCommand(initCmd); root.AddCommand(validateCmd); root.AddCommand(versionCmd); return await root.InvokeAsync(args);
