<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>StackContract.Tests</RootNamespace>
    <AssemblyName>StackContract.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\StackContract.Core\StackContract.Core.csproj" />
    <ProjectReference Include="..\..\src\StackContract.Compose\StackContract.Compose.csproj" />
    <ProjectReference Include="..\..\src\StackContract.Env\StackContract.Env.csproj" />
    <ProjectReference Include="..\..\src\StackContract.AppSettings\StackContract.AppSettings.csproj" />
    <ProjectReference Include="..\..\src\StackContract.Options\StackContract.Options.csproj" />
    <ProjectReference Include="..\..\src\StackContract.Engine\StackContract.Engine.csproj" />
    <ProjectReference Include="..\..\src\StackContract.Cli\StackContract.Cli.csproj" />
    <ProjectReference Include="..\..\src\StackContract.AspNetCore\StackContract.AspNetCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Fixtures/**/*" CopyToOutputDirectory="PreserveNewest" LinkBase="Fixtures" />
  </ItemGroup>
</Project>
